#!/bin/bash
# 9AWI Production Deployment Script
# Vercel + Render + Supabase + Upstash

set -e

echo "=========================================="
echo "  9AWI Production Deployment Script"
echo "=========================================="
echo ""

# Colors
RED='\033[0;31m'
GREEN='\033[0;32m'
YELLOW='\033[1;33m'
BLUE='\033[0;34m'
NC='\033[0m' # No Color

# Check if required tools are installed
check_tool() {
    if ! command -v $1 &> /dev/null; then
        echo -e "${RED}Error: $1 is not installed${NC}"
        exit 1
    fi
}

echo -e "${BLUE}Checking required tools...${NC}"
check_tool "git"
check_tool "curl"
check_tool "openssl"

echo ""
echo -e "${GREEN}✓ All required tools are installed${NC}"
echo ""

# Step 1: Generate JWT Secret
echo -e "${BLUE}Step 1: Generating JWT Secret...${NC}"
JWT_SECRET=$(openssl rand -hex 32)
echo -e "${GREEN}✓ JWT Secret generated${NC}"
echo ""

# Step 2: Generate Cookie Secret
echo -e "${BLUE}Step 2: Generating Cookie Secret...${NC}"
COOKIE_SECRET=$(openssl rand -hex 32)
echo -e "${GREEN}✓ Cookie Secret generated${NC}"
echo ""

# Step 3: Create production env files
echo -e "${BLUE}Step 3: Creating production env files...${NC}"

# Backend .env.production
cat > backend/.env.production << EOF
# Backend 9AWI — variables d'environnement (production Render)
# Generated by deploy.sh on $(date)

DATABASE_URL="postgresql://postgres.[YOUR_SUPABASE_REF]:[YOUR_PASSWORD]@aws-0-[REGION].pooler.supabase.com:6543/postgres"
REDIS_URL="rediss://default:[YOUR_UPSTASH_PASSWORD]@[YOUR_UPSTASH_ENDPOINT]:6379"
PORT=3001
JWT_SECRET="${JWT_SECRET}"
JWT_ACCESS_TTL="15m"
JWT_REFRESH_TTL="7d"
CORS_ORIGINS="https://[YOUR-APP].vercel.app"
EMAIL_DRIVER="smtp"
SMTP_HOST="smtp.gmail.com"
SMTP_PORT="587"
SMTP_SECURE="false"
SMTP_USER="yosricoach@gmail.com"
SMTP_PASS="[YOUR_APP_PASSWORD]"
MAIL_FROM="9AWI <yosricoach@gmail.com>"
SUPABASE_URL="https://[YOUR-REF].supabase.co"
SUPABASE_SERVICE_ROLE_KEY="[YOUR_SERVICE_ROLE_KEY]"
SUPABASE_ANON_KEY="[YOUR_ANON_KEY]"
SUPABASE_EXERCISE_BUCKET="exercise-images"
WEB_APP_URL="https://[YOUR-APP].vercel.app"
COOKIE_SECURE="true"
EOF

# Web .env.production
cat > web/.env.production << EOF
# Web 9AWI — variables d'environnement (production Vercel)
# Generated by deploy.sh on $(date)

NEXT_PUBLIC_API_URL="https://[YOUR-BACKEND].onrender.com/api"
SERVER_API_URL="https://[YOUR-BACKEND].onrender.com/api"
NEXT_PUBLIC_APP_URL="https://[YOUR-APP].vercel.app"
NEXT_PUBLIC_SUPABASE_URL="https://[YOUR-REF].supabase.co"
NEXT_PUBLIC_SUPABASE_ANON_KEY="[YOUR_ANON_KEY]"
EOF

echo -e "${GREEN}✓ Production env files created${NC}"
echo ""

# Step 4: Update vercel.json with backend URL
echo -e "${BLUE}Step 4: Updating vercel.json...${NC}"
echo -e "${YELLOW}⚠ Remember to update the backend URL in web/vercel.json${NC}"
echo ""

# Step 5: Commit changes
echo -e "${BLUE}Step 5: Committing deployment config...${NC}"
git add -A
git commit -m "feat: production deployment config (Vercel + Render + Supabase + Upstash)" || true

echo -e "${GREEN}✓ Changes committed${NC}"
echo ""

# Summary
echo "=========================================="
echo "  Deployment Summary"
echo "=========================================="
echo ""
echo -e "${GREEN}✓ JWT Secret: ${JWT_SECRET:0:16}...${NC}"
echo -e "${GREEN}✓ Cookie Secret: ${COOKIE_SECRET:0:16}...${NC}"
echo ""
echo -e "${BLUE}Next Steps:${NC}"
echo ""
echo "1. Supabase (https://supabase.com)"
echo "   - Create project '9awi-prod'"
echo "   - Update DATABASE_URL in backend/.env.production"
echo ""
echo "2. Upstash (https://upstash.com)"
echo "   - Create Redis database '9awi-redis'"
echo "   - Update REDIS_URL in backend/.env.production"
echo ""
echo "3. Render (https://render.com)"
echo "   - Create Web Service from GitHub repo"
echo "   - Set env vars from backend/.env.production"
echo "   - Deploy backend"
echo ""
echo "4. Vercel (https://vercel.com)"
echo "   - Import GitHub repo, root: web"
echo "   - Set env vars from web/.env.production"
echo "   - Deploy web"
echo ""
echo "5. UptimeRobot (https://uptimerobot.com)"
echo "   - Add HTTP monitor for backend health endpoint"
echo "   - URL: https://[YOUR-BACKEND].onrender.com/api/health"
echo ""
echo "6. GitHub Actions"
echo "   - Add secret RENDER_HEALTH_URL"
echo "   - URL: https://[YOUR-BACKEND].onrender.com/api/health"
echo ""
echo -e "${GREEN}Done! Your app will be deployed to production.${NC}"
echo ""
echo "For detailed instructions, see DEPLOYMENT.md"
